jdbc.driver = com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3307/productDB?useSSL=false
jdbc.username = root
jdbc.password = root

#
# connection pool
#
connection.pool.initialPoolSize = 5
connection.pool.minPoolSize = 5
connection.pool.maxPoolSize = 20
connection.pool.maxIdleTime = 3000

# Hibernate Configuration
hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update